### PR TITLE
[Day-10] Resume bootstrap

### PR DESCRIPTION
**Pull request by bharathyes**
### Development:
1. Get the template design from [Startbootstrap Resume](https://startbootstrap.com/previews/resume)
    1. Sticky Sidebar
    2. Embedded Images and properties
    3. Media query - responsive on screen size
    4. Viewport full height
    5. Content centering
    6. Linking within page

2. Host this on Firebase  [Resume on firebase](https://resume-28e17.web.app/)

### Screenshot
Screenshot

<a href="https://gitpod.io/#https://github.com/eternals-school/D100/pull/20"></a>

### CODE REVIEW

**Comment by nivendha** [comment]
Please update PR with correct images and font family variaotions and color

**Comment by bharathyes** [comment]
@nivendha Is `norepeat` needed only for `background-image` property or even when using `img` tag?

**Comment by nivendha** [comment]
@bharathyes `norepeat` is a a value `background-image`  only ,for  img not needed

**Comment by nivendha** [comment]
Please chcek mobile resolution , page doenot fit properly,you see a scroll in x asis

**Comment by bharathyes** [comment]
@nivendha  Mobile width has been fixed.

**Review by nivendha — APPROVED** [review]

**Pull request merged**
